name: 'Setup'
description: 'Initializes Node, PNPM and Turbo'
runs:
  using: 'composite'
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v6
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/setup@v2
      with:
        cache: true

    - name: Install Depedencies
      shell: bash
      run: pnpm ci
