name: Release

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DO_NOT_TRACK: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3
        with:
          private-key: ${{ secrets.CHANGESETS_PRIVATE_KEY }}
          client-id: ${{ secrets.CHANGESETS_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'mono'
      - uses: actions/checkout@v7
      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2.0.0
        with:
          github-token: '${{ steps.get_token.outputs.token }}'
          publish-script: 'pnpm changeset publish'
          version-script: 'pnpm run version'
          commit-message: '🦋 Version Packages'
          pr-draft: 'create'
