name: Release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  DO_NOT_TRACK: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.CHANGESETS_PRIVATE_KEY }}
          app-id: ${{ secrets.CHANGESETS_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'mono'
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: '${{ steps.get_token.outputs.token }}'
        with:
          commitMode: 'github-api'
          publish: 'pnpm changeset publish'
          version: 'pnpm run version'
          commit: '🦋 Version Packages'
