name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Run every 4h
    - cron: '0 */4 * * *'

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'DesselBane/mono'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.5
        with:
          configurationFile: .github/renovate-global-config.json5
          token: '${{ steps.get_token.outputs.token }}'
