name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Which log level renovate should use see https://docs.renovatebot.com/troubleshooting/#log-debug-levels'
        default: 'INFO'
        required: true
        type: choice
        options:
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL
#  schedule:
#    # Run every 4h
#    - cron: '0 */4 * * *'

permissions:
  contents: read

env:
  DO_NOT_TRACK: 1

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'mono'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.2
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'INFO' }}
        with:
          renovate-version: full
          configurationFile: .github/renovate-global-config.json5
          token: '${{ steps.get_token.outputs.token }}'
