name: Verify

on:
  push:
    branches-ignore:
      - master


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm -w tl

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: pnpm -w tt

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm -w tl
